




.build/uno/src/mpu9250_arduino.cpp : src/mpu9250_arduino.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/mpu9250_arduino.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/mpu9250_arduino.cpp
	@true

